### ISSUE TITLE
CrashLoopBackOff Error Pod

### ISSUE THREAD

**Issue by EfraimLA** [Kong/kong-operator#1]
I got these logs and the pod returned an error state:

> chmod: /proc/self/fd/1: Permission denied
chmod: /proc/self/fd/2: Permission denied
nginx: [emerg] open() "/dev/stderr" failed (13: Permission denied)

Operator and database are ok

**Comment by EfraimLA** [comment]
Not advance?...

**Comment by gyliu513** [comment]
It has been fixed at https://github.com/Kong/kong/issues/5708#issuecomment-606006661
