### ISSUE TITLE
Spike: Kong Gateway plugins distribution

### ISSUE THREAD

**Issue by programmer04** [Kong/kong-operator#113]
## Problem Statement

Custom plugins are a large part of customer deployments, but getting these plugins deployed and configured with a Kong Gateway instance has been painful. Since KGO aims to offer the E2E operational model for Kong Gateway on Kubernetes it should provide a way to ship and use custom plugins with Kong Gateways deployed and managed by KGO. 

## Additional Information

Documents to get familiar with

- [Kong Gateway Plugin Distribution](https://docs.google.com/document/d/1fGPjikjqSRW-jNtKgzzMVi2rUSXY1XvwZOaPMPA1dtM)
- [Kong Custom Plugin Management for Kubernetes](https://docs.google.com/document/d/1T9GNeBf9sSzMSKE7pAJXVc8MpDPVWXNFvDKVWcmFwSw)
- [Product Brief: Custom Plugin Streaming](https://konghq.atlassian.net/wiki/spaces/PM/pages/3391291407/Product+Brief+Custom+Plugin+Streaming)
- [Engineering brief](https://docs.google.com/document/d/1-gYEaf_31BR_QXmZXNhy0bOrXYJ4X_cXobQ_vbLDIhE/edit#heading=h.9ikojn8u15x)

## Acceptance Criteria
- [x] based on documents mentioned above spike the option and effort to provide Kong Gateway plugins distribution in KGO (if the implementation is sufficiently complex or consensus is hard to achieve, then the result of this issue should be a design doc)
- [ ] create an action plan for implementing this - prepare issues with clear acceptance criteria and prioritize them

**Comment by lahabana** [comment]
Issue for action plan: #371
