### ISSUE TITLE
Use renovate to automatically update non-standard dependencies

### ISSUE THREAD

**Issue by programmer04** [Kong/kong-operator#121]
## Problem Statement

Currently, some non-standard dependencies need manual updates. It is mentioned in the release procedure.

## Proposed Solution

Use the same approach for updating such dependencies as in KIC - leverage Renovate to do it.

## Acceptance Criteria
- [ ] those dependencies are governed by Renovate
- [ ] release procedure is updated

**Comment by programmer04** [comment]
Some work has been done in https://github.com/Kong/gateway-operator/pull/85, but still renovate has to be enabled for the whole repo

**Comment by czeslavo** [comment]
Reopening for Helm upgrade tests automatic bumps.
