### ISSUE TITLE
Migrate Project layout to Kubebuilder v4

### ISSUE THREAD

**Issue by pmalek** [Kong/kong-operator#130]
### Problem statement

This project has used Kubebuilder's v3 layout for quite some time now.

There already exists a new version of that: [v4](https://book.kubebuilder.io/plugins/go-v4-plugin) which has several benefits (described e.g. in Kong/gateway-operator-archive#1455).

The biggest one is that it makes the controller code be placed in `internal/` and hence precluding OSS users from relying on our implementation. This would most definitely save some headaches in the future.

Kong/gateway-operator#1455 has been merged with the above in mind (and more, see PR description for more details) but has  proven to be disruptive to [1.2](https://github.com/Kong/gateway-operator/milestone/30) work.

This issue tries to capture the effort to migrate to Kubebuilder v4 layout in a better time frame. Potentially after Kong/gateway-operator-enterprise#68 and Kong/gateway-operator-enterprise#70 (and its potential sub-issues) are complete and all the EE work has also been completed.

Adding `nice-to-have` label as that's what this issue is. Ideally, targeting 1.2 release.

### Proposed solution

- reapply patch from Kong/gateway-operator#1455, Kong/gateway-operator-archive#1462 and Kong/gateway-operator-archive#1463

### Important notes

This change will incur a breaking change for Go API consumers and has to be properly communicated and coordinated for internal users, specifically CG dataplane-controller (see: https://github.com/search?q=repo%3AKong%2Fdataplane-controller%20github.com%2Fkong%2Fgateway-operator%2Fapis&type=code)

### Acceptance criteria

- [x] Redo Kong/gateway-operator#1455 when Kong/gateway-operator-enterprise#68 and Kong/gateway-operator-enterprise#70 are complete and EE work has been done to accommodate changes form those issues.
- [x] This change has a breaking change note in docs and in https://github.com/Kong/gateway-operator/blob/main/CHANGELOG.md
- [ ] Update to a version that implements this change is coordinated with usage in CG dataplane-controller (https://github.com/search?q=repo%3AKong%2Fdataplane-controller%20github.com%2Fkong%2Fgateway-operator%2Fapis&type=code)

**Comment by pmalek** [comment]
I've updated the acceptance criteria in this issue.

This is a breaking change for Go API consumers and needs to be documented as such.

Most importantly CG dataplane controller code has to be updated to include this change (https://github.com/search?q=repo%3AKong%2Fdataplane-controller%20github.com%2Fkong%2Fgateway-operator%2Fapis&type=code)

cc: @programmer04

**Comment by programmer04** [comment]
PR for CG dataplane has been created https://github.com/Kong/dataplane-controller/pull/554

**Comment by pmalek** [comment]
To be done after release:

- use 1.3.0 (when released) in https://github.com/Kong/dataplane-controller/pull/554

**Comment by randmonkey** [comment]
@pmalek I see the acceptance criteria are all met in the issue. Should we close this?

**Comment by pmalek** [comment]
The comment above captures what needs to be done in dataplane controller. The intention was to leave this open until that is done.

Wie can also move this part of the task to team-K8s repo and close those one here

**Comment by programmer04** [comment]
I'm on it, just after the Monday release I'll make https://github.com/Kong/dataplane-controller/pull/554 ready to merge

**Comment by lahabana** [comment]
@programmer04 should we push for the PR to be merged?

**Comment by programmer04** [comment]
Yes, I think sooner is better

**Comment by programmer04** [comment]
The PR https://github.com/Kong/dataplane-controller/pull/660 has been merged it's resolved
