### ISSUE TITLE
Conformance tests flakiness for computational requirements reason

### ISSUE THREAD

**Issue by mlavacca** [Kong/kong-operator#134]
## Problem Statement

https://github.com/Kong/gateway-operator-archive/pull/1381 enabled again the conformance tests, updating the suite to the experimental one that creates the report. At the time of re-enablement, there was only one enabled test, and no flakes happened.

https://github.com/Kong/gateway-operator-archive/pull/1398 enabled many more conformance tests. This caused the test suite to be very flaky, as the amount of computational resource needed by such a suite is quite high, because of the combination of long-lived and short-lived `Gateway`s. The tests are successful when run in local environments, but flaky in the free GH runners.

## Acceptance criteria

- [ ] the conformance tests are re-enabled
- [ ] the conformance tests are run in machines with a higher amount of resources than the free GH runners.

**Comment by shaneutt** [comment]
So are the options:

a) reworking code to improve resource utilization
b) reducing the parallelization of tests
c) paying for premium CI service
d) some combination of the above

?

**Comment by pmalek** [comment]
`a` and `b`: that would be the upstream change right? @mlavacca mentioned that this comes from the fact that the suite creates several (7?) `Gateway`s which in turn translate into the same number of Kong Gateway + KIC instances running which might be too much for default (free) Github runners.

`c` is an option but as always, this would take time

**Comment by mlavacca** [comment]
Yes, the problem is with the long-lived gateways (4) that are created upfront by the suite. In addition to those, some tests create ad-hoc gateways. even in case there is no parallelism, we need to deal with 5 (4+1) Gateways at the same time. Changing this behavior would require a massive upstream change (that I do not think will ever happen).

`c` is the lowest hanging fruit. We could consider running conformance tests on nightly tests, instead of after every push, to reduce costs.

**Comment by shaneutt** [comment]
I understand the appeal of `c`, especially when we feel a little crunched for the `v1.2.0` release.

Before I read:

> Changing this behavior would require a massive upstream change (that I do not think will ever happen).

My default position would have been to advocate for `a` and `b` because investing in upstream (when managed well) can have lots of ancillary benefits.

Can you elaborate some on your assessment?

**Comment by mlavacca** [comment]
> I understand the appeal of c, especially when we feel a little crunched for the v1.2.0 release.

conformance is a stretch goal for 1.2, and automatic conformance tests in CI isn't something we should be concerned about for 1.2. In case we reach core conformance in time for 1.2, we can just run the suite locally and upload the report.

> Can you elaborate some on your assessment?

The conformance tests create 4 gateways upfront, that are used by many httproute tests. Those tests do not need specific gateway configurations to be run, therefore they just create the route and use the default gateways (e.g., https://github.com/kubernetes-sigs/gateway-api/blob/main/conformance/tests/httproute-simple-same-namespace.yaml). Others need specific gateways (e.g., https://github.com/kubernetes-sigs/gateway-api/blob/main/conformance/tests/gateway-modify-listeners.yaml). Changing this behavior upstream would require getting rid of the shared gateways, and refactoring many tests to let them create and use ad-hoc gateways. 

In a scenario where we perform such a refactoring upstream, the following are my thoughts:
**PRO**: the amount of resources needed would be limited to 1 gateway at a time (in case no parallelism is activated). We'd fix this issue.

**CONS**: the suite would take waaaaaay longer to execute, as there would be no gateway created upfront. Gateways need >1 minute on the local machine (in CI the time is much higher) to get ready. If every single test creates a short-lived ad-hoc gateway, the time for the suite to be run would dramatically increase. Result: conformance tests would take too much time to be executed, even in a local machine (can't imagine in CI).

**Comment by shaneutt** [comment]
Yeah, I suppose another CON would be less chance for the tests to illuminate order of operation issues. I don't know that I have much more to say, it might just come down to what `c` costs and if we're OK with that cost.
