### ISSUE TITLE
basic documentation for Kong Operator

### ISSUE THREAD

**Issue by hbagdi** [Kong/kong-operator#18]
- Write up basic documentation on how to get started with Operator on k8s and Openshift.
- Capabilities of Kong Operator
- Doc on how to configure Kong settings (point them to helm chart doc once the doc explain how to use them)

**Comment by hbagdi** [comment]
xref https://github.com/operator-framework/community-operators/issues/351

**Comment by mrhillsman** [comment]
@hbagdi any update on this?
