### ISSUE TITLE
CI: Test the "vanilla" operator at HEAD

### ISSUE THREAD

**Issue by mflendrich** [Kong/kong-operator#20]
Implement a GitHub Actions workflow which:
- spins up a Kubernetes cluster (e.g. `microk8s` with `dns`, `rbac`, `registry` addons)
- builds the operator from HEAD and pushes to the local registry
- runs the operator from the image built in the previous step
- deploys an example `Kong`
- waits until Kong is up
- deploys an example `Ingress`
- makes an HTTP request to validate that the ingress controller handled the request properly

**Comment by mflendrich** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [[mflendrich] CI/CD for operator](https://trello.com/c/csAFYHiL/489-mflendrich-ci-cd-for-operator)

**Comment by hbagdi** [comment]
All CI that we setup should ensure that anonymous reports are turned off in kong and the controller.
- https://github.com/Kong/kong/blob/master/kong.conf.default#L128
- --anonymous-reports in https://github.com/Kong/kubernetes-ingress-controller/blob/master/docs/references/cli-arguments.md

**Comment by mflendrich** [comment]
To clarify the scope, this issue deals with the "vanilla" flavor of kong-operator, as opposed to the RH-certified flavor as delivered in #24.
