### ISSUE TITLE
Introduce a standardized mechanism for patch releases

### ISSUE THREAD

**Issue by mlavacca** [Kong/kong-operator#207]
## Problem Statement

We need a mechanism to backport fixes into release branches and cut releases without manually branching out and backporting all the needed contributions. We already have a similar mechanism in KIC that we could easily reuse here.

## Proposed Solution

Reuse the same pipelines we already have in KIC to backport fixes and release patch versions on top of already existing releases.

## Acceptance Criteria
- [x] the Backport workflow allows to backport fixes through labels, fixed by #237 
- [x] the release procedure is updated with instructions on how to release minor and patch releases and the differences between them.

**Comment by pmalek** [comment]
KIC has [backport workflow](https://github.com/Kong/kubernetes-ingress-controller/blob/cefe68030ca9cc2a0b02b140fac1c2129f040bf4/.github/workflows/backport.yaml) which has the problem of conflicts (these mostly happen when there's a change in CHANGELOG).

It would basically be a copy-paste of the workflow but that would still has this issue and require manually backporting in case of conflicts. There is no such feature ( to exclude changes from a provided path(s) in the action that we use https://github.com/tibdex/backport ). So we either fork it an implement ( possibly too much effort ) or leave with the flawed workflow of manual backporting in case of conflicts.

---

As for the patch releases: I'm not aware of any process/automation that we'd have in place for KIC's release branch. Those are pushed manually whenever we decide to branch off, no?

**Comment by mlavacca** [comment]
> KIC has [backport workflow](https://github.com/Kong/kubernetes-ingress-controller/blob/cefe68030ca9cc2a0b02b140fac1c2129f040bf4/.github/workflows/backport.yaml) which has the problem of conflicts (these mostly happen when there's a change in CHANGELOG).
> 
> It would basically be a copy-paste of the workflow but that would still has this issue and require manually backporting in case of conflicts. There is no such feature ( to exclude changes from a provided path(s) in the action that we use https://github.com/tibdex/backport ). So we either fork it an implement ( possibly too much effort ) or leave with the flawed workflow of manual backporting in case of conflicts.

Yep, at least for now I'd simply copy-paste the workflow we already have in KIC.

> As for the patch releases: I'm not aware of any process/automation that we'd have in place for KIC's release branch. Those are pushed manually whenever we decide to branch off, no?

yes, they are manually pushed. What we mostly need to do in this regard here is updating our release procedure to include patch release instructions as well.
