### ISSUE TITLE
Allow setting ExternalTrafficPolicy for k8s dataplane proxy service

### ISSUE THREAD

**Issue by sentinelleader** [Kong/kong-operator#231]
## Problem Statement
For cloud providers like azure and gcp, they dont support proxy protocol and the only way to setup client ip preservation is by setting `ExternalTrafficPolicy` to `local` in the lb service spec. Currently KGO don't expose setting this for the dataplane service
...

## Proposed Solution

Extend `ServiceOptions` to include more k8s service overrides

## Additional Information

https://techcommunity.microsoft.com/t5/fasttrack-for-azure/how-client-source-ip-preservation-works-for-loadbalancer/ba-p/3033722

**Comment by pmalek** [comment]
@sentinelleader #241 contains the draft of API change.

**Comment by pmalek** [comment]
#241 has been merged. It's already available in nightly and will land in 1.3
