### ISSUE TITLE
conformance: `HTTPRouteInvalidBackendRefUnknownKind` tests

### ISSUE THREAD

**Issue by programmer04** [Kong/kong-operator#271]
## Problem Statement

KIC ControlPlane is already HTTP core conformant; the test `HTTPRouteInvalidBackendRefUnknownKind ` is part of it. We need to run such a core test successfully.

## Acceptance Criteria
- [ ] The core test `HTTPRouteInvalidBackendRefUnknownKind ` is successfully run.

**Comment by pmalek** [comment]
~Blocked by https://github.com/Kong/kubernetes-ingress-controller/pull/6104~

**Comment by lahabana** [comment]
Goal here seems to be to run conformance tests without admission webhook like explained in:

https://github.com/Kong/kubernetes-ingress-controller/pull/6104#issuecomment-2137828852

**Comment by pmalek** [comment]
> Goal here seems to be to run conformance tests without admission webhook like explained in:
> 
> [Kong/kubernetes-ingress-controller#6104 (comment)](https://github.com/Kong/kubernetes-ingress-controller/pull/6104#issuecomment-2137828852)

Correct, this is blocked now by https://github.com/Kong/gateway-operator/issues/308
