### ISSUE TITLE
Put OLM files to this repo

### ISSUE THREAD

**Issue by gyliu513** [Kong/kong-operator#3]
I think we should put the OLM files to this repo as well, then after the OLM files are stable, we can contribute to https://github.com/operator-framework/community-operators/tree/master/upstream-community-operators/kong , comments? Thanks!

**Comment by hbagdi** [comment]
Can you elaborate what you mean by OLM files?

**Comment by hbagdi** [comment]
Sorry, closed it by mistake.

**Comment by gyliu513** [comment]
@hbagdi OLM is `operator lifecycle manager`, including files like CSV file, CRD etc, please refer to https://github.com/IBM/operand-deployment-lifecycle-manager/tree/master/deploy/olm-catalog/operand-deployment-lifecycle-manager as an example.

**Comment by gyliu513** [comment]
This is the olm files for Kong https://github.com/operator-framework/community-operators/tree/master/upstream-community-operators/kong

**Comment by hbagdi** [comment]
I see what you mean, could you please PR it?

**Comment by gyliu513** [comment]
sure, let me create a PR soon. Thanks @hbagdi
