### ISSUE TITLE
Release workflow will run two `create-release-pr` jobs when releasing from `main` branch 

### ISSUE THREAD

**Issue by randmonkey** [Kong/kong-operator#356]
## Current Behavior

The release workflow will create 2 jobs to create PR to `main` branch when the input base branch of release workflow is `main` itself.
https://github.com/Kong/gateway-operator/actions/runs/9594711978/job/26458832964
## Expected Behavior

Only one PR made when base branch is `main`.

## Steps To Reproduce

Run release action from `main` branch

## Operator Version

current `main`

**Comment by pmalek** [comment]
This should be fixed by https://github.com/Kong/gateway-operator/pull/357, which is already merged.

If this reoccurs, let's reopen.
