### ISSUE TITLE
New CRD for custom Kong Plugin installation

### ISSUE THREAD

**Issue by programmer04** [Kong/kong-operator#378]
## Problem Statement

A new CRD for dealing with Kong Plugins is needed. It needs to have well-thought fields that won't require changes in the future it should be extensible and take into account adding in the foreseeable future.

- https://github.com/Kong/gateway-operator/issues/372

Of course, fields for signature verification are **not in the scope** of this issue. 

Related Kubernetes controller typical boilerplate has to be generated too.

## Proposed Solution

There is an [initial proposition presented in Kong Gateway Plugins distribution](https://docs.google.com/document/d/1-gYEaf_31BR_QXmZXNhy0bOrXYJ4X_cXobQ_vbLDIhE/edit#heading=h.3tn2kjmrw2q5) that can be used as a starting point, inspiration. Naming hasn't been decided yet the proposed options for now are
- `KongPluginInstallation`
- `KongPluginInstance`

## Acceptance Criteria
- [ ] There is a new CRD with well thought fields that serves the purpose and all boilerplate

**Comment by lahabana** [comment]
Do not forget to consider status as well
