### ISSUE TITLE
Make object counters conditional on the presence of CRDs in the cluster

### ISSUE THREAD

**Issue by pmalek** [Kong/kong-operator#448]
### Problem statement

Objects counters should not report errors when the respective CRDs are missing from the cluster.

#360 addressed that for AIGateway but we should do the same for `ControlPlane`s.

### Acceptance criteria

- [ ] No errors should be reported from objects counters when the respective controllers are disabled and CRDs missing.

**Comment by lahabana** [comment]
Apparently something similar is already done in KIC so it should be straightforward to fix
