### ISSUE TITLE
Konnect entities: Consumer's group assignment

### ISSUE THREAD

**Issue by pmalek** [Kong/kong-operator#519]
### Problem statement

After #436 and #514 are implemented we can now implement assigning consumers to a group.

### Proposed solution

- Request declarative group assignment API
  - https://kongstrong.slack.com/archives/C03LRB400TC/p1724411291389629
- Use `Consumer`'s group field: https://github.com/Kong/kubernetes-configuration/blob/9ac1d3cf7906e01a6bf14979fef9418195b2053e/api/configuration/v1/kongconsumer_types.go#L56-L59 for assigned groups

### Acceptance criteria

- [ ] KGO can assign `Consumer`s to `ConsumerGroups` in Konnect based on the groups field

**Comment by czeslavo** [comment]
Marking as blocked as we still do not have the declarative ConsumerGroup membership assignment implemented in the Konnect API: https://konghq.atlassian.net/browse/KOKO-1952

**Comment by lahabana** [comment]
We shouldn't expect a declarative API anytime soon and do the state tracking on our side.

This is therefore unblocked.
