### ISSUE TITLE
conformance: `GatewayInvalidTLSConfiguration` test

### ISSUE THREAD

**Issue by mlavacca** [Kong/kong-operator#54]
## Problem Statement

KIC `ControlPlane` is already HTTP core conformant; the test `GatewayInvalidTLSConfiguration` is part of it. We need to run such a core test successfully. 

## Acceptance Criteria

- [ ] The core test `GatewayInvalidTLSConfiguration` is successfully run.

**Comment by lahabana** [comment]
@mlavacca was there any specific reason to remove this from 1.3?

**Comment by mlavacca** [comment]
> @mlavacca was there any specific reason to remove this from 1.3?

my bad, it should be in the 1.3 milestone
