### ISSUE TITLE
conformance: `HTTPRouteMethodMatching` feature

### ISSUE THREAD

**Issue by mlavacca** [Kong/kong-operator#58]
## Problem Statement

KIC `ControlPlane` is already conformant with the `HTTPRouteMethodMatching` extended feature; we need to enable such a feature and pass the related conformance tests.

## Acceptance Criteria

- [ ] The feature `HTTPRouteMethodMatching` is enabled and the related conformance tests are successfully run.

**Comment by lahabana** [comment]
@mlavacca any reason to remove this from 1.3?

**Comment by pmalek** [comment]
This was just a switch flip so: #335.
