### ISSUE TITLE
Support for defining service account in kong manifest 

### ISSUE THREAD

**Issue by piyushpgupta** [Kong/kong-operator#59]
i want to define service account be to used when creating the kong pod from kong operator.
currently that support is provided in the Ingress Controller parameters.

is similar options can be provided to the  kong configuration  and possible for side car container.

**Comment by rainest** [comment]
The service account was originally created for the controller and later used for other purposes outside it. We never moved the configuration location to avoid a breaking change, but the account configured under the controller section _will_ actually be used for both.

At present the only other setting that makes use of it is the PodSecurityPolicy, so it's only set [if that or the controller are enabled](https://github.com/Kong/charts/blob/bd8e8600f708a956e4041ec84d6a0814e1fbcfd2/charts/kong/templates/deployment.yaml#L61-L63). If you need to use it for something else, please open an issue on that charts repo referencing this issue (it'll be added there and we'll update the version of the chart included in the operator after).
