### ISSUE TITLE
Konnect entities: index `KongService`s in the `KongPlugin` reconciler

### ISSUE THREAD

**Issue by mlavacca** [Kong/kong-operator#596]
## Problem Statement

https://github.com/Kong/gateway-operator/pull/550 introduced the KongPlugin Reconciler. Such a reconciler
fetches all the entities from the Kubernetes cluster to understand which are referring to the reconciled `KongPlugin`. This operation is inefficient, as we could index the entities based on the `konghq.com/plugins` annotation to filter out upfront the ones that do not reference the KongPlugin under reconciliation.

As a side effect of this indexing, we'll need to move the whole KongService finalizer logic into separate controllers. The generic reconcile is a good candidate for it. We could think of a generic logic that fetches the targeting `KongPluginBinding`s, and add/remove the finalizer based on them and the entity's deletion timestamp.

## Note

As a first implementation, the only entity reconciled is KongService, but the same logic applies to `KongRoute`, `KongConsumer`, and `kongConsumerGroup`.

## Acceptance Criteria

- [ ] The kong entities are indexed by the referenced KongPlugin names (via `konghq.com/plugins` annotation).
- [ ] The entity's finalizer logic is extracted from the `KongPlugin` controller into the generic reconciler.

**Comment by mlavacca** [comment]
Blocked by https://github.com/Kong/gateway-operator/pull/550

**Comment by pmalek** [comment]
The finalizer logic has been moved in #611.

As far as I believe if we'd like to use the indices for listing of `KongService`s in https://github.com/Kong/gateway-operator/blob/0f964e8eb2ead67297d4b3def63a12120b0785f1/controller/konnect/reconciler_kongplugin.go#L94-L105 we would only get the `KongService`s that use the plugin (through annotation) and thus we would not be able to act on the removal of those annotations when `KongPluginBinding` has to be removed or updated, right?

**Comment by pmalek** [comment]
After a chat with @mlavacca we're good now to close it after #644 has been merged.
