### ISSUE TITLE
How to config volume of the postgres

### ISSUE THREAD

**Issue by icarhunter** [Kong/kong-operator#62]
I want to config the volume of the postgres,just like nfs,cephfs,but I don't find explain or demo from kong-operator document

**Comment by rainest** [comment]
The Postgres instance that the operator can deploy alongside Kong uses the https://github.com/bitnami/charts/tree/master/bitnami/postgresql chart. Any settings available there can be set under the `postgresql` section of the Kong CR spec.

I'm not sure exactly what you're looking for (`storageClass`, perhaps?), but if it's not available in those settings, you'd want to instead set up a Postgres instance independent of the Kong instance and add configuration (`pg_host` under `env` and such) to use it.
