### ISSUE TITLE
convert this to a Go based operator

### ISSUE THREAD

**Issue by gyliu513** [Kong/kong-operator#7]
@hbagdi can you please share me some plan for this? If no one is working for this, I would like to work for this as priority.

FYI @morvencao @morningspace

**Comment by mflendrich** [comment]
Thanks @gyliu513 for your idea and motivation.

Rewriting the operator in Go is a major update which is further down on our roadmap. Currently our focus is on improving usability of the Helm operator - the added possibilities with a Go operator (which are not handled by KIC which is a Go operator today, or by the helm chart we have today) do not seem justified by the added maintenance burden.

I'm closing this issue with an intention to reopen when we're ready to upgrade to a Go-based operator.
