### ISSUE TITLE
Can't create Kong on Openshift 4.9.0

### ISSUE THREAD

**Issue by nautiam** [Kong/kong-operator#71]
I install Kong-operator on Openshift 4.9.0 from RedHat Marketplace and get this error:

`
failed to install release: template: kong/templates/ingress-class.yaml:2:34: executing "kong/templates/ingress-class.yaml" at <lookup "networking.k8s.io/v1" "IngressClass" "" "kong">: error calling lookup: ingressclasses.networking.k8s.io "kong" is forbidden: User "system:serviceaccount:openshift-operators:kong-operator" cannot get resource "ingressclasses" in API group "networking.k8s.io" at the cluster scope
`

**Comment by shaneutt** [comment]
Thank you for reporting this problem, and for posting your workaround.

Our expectation is that this should work with the latest release as the relevant permissions are present:

- https://github.com/Kong/kong-operator/blame/main/deploy/role.yaml#L13-L19
- https://github.com/Kong/kong-operator/blame/fork/0.9.0-certified/deploy/role.yaml#L21-L27

However we're investigating an issue that has occurred with upstream publishing to the Redhat Marketplace which may have had an effect on this. Let us know in the meantime if there are other questions or concerns we can address for you, otherwise we'll report back once we have confirmed resolution for the marketplace publishing issue.

**Comment by rainest** [comment]
@nautiam does this work using the version currently available at https://operatorhub.io/operator/kong ?

If so that should confirm that the latest permissions are correct and it's just an issue with the Marketplace copy of the package being out of date.

**Comment by nautiam** [comment]
@rainest I only tested with Kong from Marketplace of Openshift. I don't test with Kong from Operatorhub

**Comment by rainest** [comment]
Right, I mean can you test with the one from Operator Hub? While we're working out the issue with the Marketplace listing, it'd be useful to confirm if there's something actually wrong with the permission we added or if the Marketplace version was just missing the latest update.

**Comment by rainest** [comment]
@nautiam we're still working with Red Hat regarding the status of the Marketplace listing. Had you had a chance to try with the Operator Hub version to see if it exhibits the issue still?

**Comment by nautiam** [comment]
> @nautiam we're still working with Red Hat regarding the status of the Marketplace listing. Had you had a chance to try with the Operator Hub version to see if it exhibits the issue still?

Sorry I missed your last reply.

I tested kong-operator v0.9.0 from Operator Hub on Openshift and this issue still happens.
> failed to install release: template: kong/templates/ingress-class.yaml:2:34: executing "kong/templates/ingress-class.yaml" at <lookup "networking.k8s.io/v1" "IngressClass" "" "kong">: error calling lookup: ingressclasses.networking.k8s.io "kong" is forbidden: User "system:serviceaccount:openshift-operators:kong-operator" cannot get resource "ingressclasses" in API group "networking.k8s.io" at the cluster scope

**Comment by rainest** [comment]
Ah, okay, I see now--we have it `deploy/role.yaml`, but when OLM handles the install, it generates the role from the CSV info, which is quite out of date: https://github.com/Kong/kong-operator/blob/main/olm/0.9.0/kong.v0.9.0.clusterserviceversion.yaml#L60-L130

**Comment by mflendrich** [comment]
We're working on a release of [Gateway Operator](https://github.com/Kong/gateway-operator) that a technical preview of is expected to come at the end of September.

From now on, Gateway Operator will supersede the Helm operator as per our [deprecation notice](https://github.com/Kong/kong-operator#deprecation-notice).

**Comment by pmalek** [comment]
For those interested to learn about the Gateway Operator you can find that info:

- https://incubator.konghq.com/p/gateway-operator
- https://github.com/Kong/gateway-operator-docs
- and here for Redhat listing https://catalog.redhat.com/software/containers/kong/gateway-operator-bundle/6318fdd1e3a1ad503fedef23

As @mflendrich mentioned. This is marked as Technical Preview.
