### ISSUE TITLE
Install docs for non-OperatorHub setup

### ISSUE THREAD

**Issue by sepulworld** [Kong/kong-operator#75]
Hi! We don't use the OperatatorHub. The quickstart references the using the OperatorHub. When I install kong-operator via a Helm chart install directly it appears to be missing some CRDs?

After kong-operator helm install I try to add an Ingress and get an error:

```
no matches for kind "Kong" in group "configuration.konghq.com"
```

**Comment by shaneutt** [comment]
Hi @sepulworld thanks for getting in touch,

We're actually in the process of deprecating this repository (more details [in the README.md](https://github.com/Kong/kong-operator#deprecation-notice)) and we're now working on a [Golang-based Operator](https://github.com/kong/operator) to replace it. In the meantime we recommend using the [Helm Chart](https://github.com/kong/charts) as the supported method for deploying Kong on Kubernetes, can you let us know if that works for you and if you run into any further troubles or have other questions/concerns?

**Comment by sepulworld** [comment]
Ah! Good to know. I figured so after seeing the Helm chart you linked a few weeks back. Perhaps add a note to README.md saying this project is depreciated
